  schemas:
   AppProfileInfoReq_1:
    properties:
      StateCode:
        type: string
      ApplicationID:
        type: string
      usrid:
        type: string
      srvid:
        type: integer
      mode:
        type: string
      pltfrm:
        type: string
   AppProfileInfoReq_2:
    properties:
      StateCode:
        type: string
      ApplicationID:
        type: string
      usrid:
        type: string
      srvid:
        type: integer
      mode:
        type: string
      pltfrm:
        type: string
  examples:
    AppProfileInfoReq_1:
      value:
        StateCode: 35
        ApplicationID: UP1500000002
        usrid: 09
        srvid: 1150
        mode: web
        pltfrm: andorid
    AppProfileInfoReq_2:
      value:
        StateCode: 35
        ApplicationID: UP1500000002
        usrid: 09
        srvid: 1150
        mode: web
        pltfrm: ios
