openapi: 3.0.1
info:
  title: Umang Services – Coffee Board API
  description: |-
      Coffee board services to be onboarded onUMANGPlatform
  termsOfService: https://web.umang.gov.in/
  contact:
    name: Umang Services – Coffee Board API
    url: https://web.umang.gov.in/customer_support
  version: 1.0.0
servers:
- url: https://app.umang.gov.in/t/negd.gov.in/umang/depttapi/cbApi/ws1
paths: