openapi: 3.0.1
info:
  title: Umang Services – Coffee Board API
  description: |-
      Coffee board services to be onboarded onUMANGPlatform
  termsOfService: https://web.umang.gov.in/
  contact:
    name: Umang Services – Coffee Board API
    url: https://web.umang.gov.in/customer_support
  version: 1.0.0
servers:
- url: https://app.umang.gov.in/t/negd.gov.in/umang/depttapi/cbApi/ws1
paths:
  /inwardstatus:
    post:
      tags:
      - Inward Status
      summary: The following APIs are used for inward status
      operationId: inwardstatus
      security:
      - bearerAuth: []
      parameters:
        - in: header
          name: Tkn
          schema:
            type: string
            example: ""
          required: true
        - in: header
          name: deptid
          schema:
            type: integer
            example: 371
        - in: header
          name: srvid
          schema:
            type: integer
            example: 1740
        - in: header
          name: subsid
          schema:
            type: integer
            example: 0
        - in: header
          name: subsid2
          schema:
            type: integer
            example: 0
        - in: header
          name: formtrkr
          schema:
            type: integer
            example: 0
      requestBody:
        content:
          application/json:
            schema:
              properties:
                  tkn:
                    type: string
                    example: rhfb3d2c6a-4518-4163-a922-fbef65d0c2c1/2
                  trkr:
                    type: string
                    example: 213132
                  lang:
                    type: string
                    example: en
                  lat:
                    type: string
                    example: 12.972
                  lon:
                    type: string
                    example: 77.595
                  lac:
                    type: string
                    example: 90
                  did:
                    type: string
                    example: 123234
                  usag:
                    type: string
                    example: 90
                  apitrkr:
                    type: string
                    example: 123234
                  usrid:
                    type: string
                    example: 09
                  srvid:
                    type: string
                    example: 1544
                  mode:
                    type: string
                    example: web
                  pltfrm:
                    type: string
                    example: andorid
                  deptid:
                    type: string
                    example: 344
                  subsid:
                    type: string
                    example: 0
                  subsid2:
                    type: string
                    example: 0
                  formtrkr:
                    type: string
                    example: 0
                  Grower_ID:
                    type: string
                    example: KA00007516
                  Inward_No:
                    type: string
                    example: EKA00036716
                  Authorization:
                    type: string
                    example: Tamil News Doordarshan Podhigai
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - $ref: "#/components/schemas/DemoAuthResponse1"
                - $ref: "#/components/schemas/DemoAuthResponse2"
              examples:
                DemoAuthResponse1:
                  $ref: "#/components/examples/DemoAuthResponse1"
                DemoAuthResponse2:
                  $ref: "#/components/examples/DemoAuthResponse2"

            application/xml:
              schema:
                  $ref: '#/components/schemas/Employees'
   
        400:
          description: Bad Request/Validation Error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Text

  schemas:
    DemoAuthResponse1:
      properties:
        rs:
          type: string
        rc:
          type: string
        rd:
          type: string
        pd:
          type: object
    DemoAuthResponse2:
      properties:
        rs:
          type: string
        rc:
          type: string
        rd:
          type: string
        pd:
          type: object


    Employees:
      type: object
      properties:
          Employee1:
            $ref: '#/components/schemas/Employee1'
          Employee2:
            $ref: '#/components/schemas/Employee2'
          Employee3:
            $ref: '#/components/schemas/Employee3'

     
    Employee1:
      type: object
      properties:
        EmpId:
            #no children
            type: string
            example: "001"
        Name:
            #no children
            type: string
            example: "Steven"
        Mobile:
            #no children
            type: string
            example: "1-541-754-3010"
        EmailId:
            #no children
            type: string
            example: "steven@yourcomany.com"
      xml:
        wrapped: true
        name: 'Employee'
    Employee2:
      type: object
      properties:
        EmpId:
            #no children
            type: string
            example: "002"
        Name:
            #no children
            type: string
            example: "Mark"
        Mobile:
            #no children
            type: string
            example: "1-551-754-3010"
        EmailId:
            #no children
            type: string
            example: "mark@yourcomany.com"
      xml:
        wrapped: true
        name: 'Employee'
    Employee3:
      type: object
      properties:
        EmpId:
            #no children
            type: string
            example: "003"
        Name:
            #no children
            type: string
            example: "Adam"
        Mobile:
            #no children
            type: string
            example: "1-551-754-3010"
        EmailId:
            #no children
            type: string
            example: "mark@yourcomany.com"
      xml:
        wrapped: true
        name: 'Employee'



  examples:
    DemoAuthResponse1:
      value:
        rs: S
        rc: 200
        rd: OK
        pd: {'Status': {'Status': 'Issued Order', 'code': 2003}, 'apiVersion': '1.0', 'success': True}
    DemoAuthResponse2:
      value:
        rs: S1
        rc: 200
        rd: OK
        pd: {'Status': {'Status': 'Issued Order', 'code': 2005}, 'apiVersion': '2.0', 'success': True}

