openapi: 3.0.1
info:
  title: UMANG NTRP Tech API v2.1
  description: |-
      Non-Tax Receipt Portal (NTRP) of Government of India enables citizens to deposit fees/fine/other money into the Government Account through a single interface.
  termsOfService: https://web.umang.gov.in/
  contact:
    name: UMANG NTRP Tech API v2.1
    url: https://web.umang.gov.in/customer_support
  version: 1.0.0
servers:
- url: https://app.umang.gov.in/t/negd.gov.in/umang/depttapi/ntrpApi/ws1
paths:
  /sendotp:
    post:
      tags:
      - Send OTP
      summary: This API will be used to send OTP.
      operationId: sendotp
      security:
      - bearerAuth: []
      parameters:
        - in: header
          name: deptid
          schema:
            type: integer
            example: 143
        - in: header
          name: srvid
          schema:
            type: integer
            example: 901
      requestBody:
        content:
          application/json:
            schema:
              properties:
                  tkn:
                    type: string
                    example: 123132132
                  trkr:
                    type: string
                    example: 12313
                  lang:
                    type: string
                    example: en
                  lat:
                    type: string
                    example: 90
                  lon:
                    type: string
                    example: 90
                  lac:
                    type: string
                    example: 90
                  usag:
                    type: string
                    example: 90
                  aud:
                    type: string
                    example: 90
                  usrid:
                    type: string
                    example: 90
                  srvid:
                    type: string
                    example: 90
                  mode:
                    type: string
                    example: web
                  pltfrm:
                    type: string
                    example: andorid
                  apitrkr:
                    type: string
                    example: 123132132
                  did:
                    type: string
                    example: null
                  deptid:
                    type: string
                    example: 901
                  subsid:
                    type: string
                    example: 23
                  subsid2:
                    type: string
                    example: 0
                  formtrkr:
                    type: string
                    example: 132132
                  emailid:
                    type: string
                    example: anil.cpsms@gmail.com
                  countrycode:
                    type: string
                    example: 91
                  mobilenumber:
                    type: string
                    example: 9910268862
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                properties:
                  rs:
                    type: string
                    example: S
                  rd:
                    type: string
                    example: Success
                  rc:
                    type: string
                    example: NT0000
                  pd:
                    type: object
                    properties:
                      ErrorCodes: 
                        type: string                        
                        example: "null"
                      ResponseStatus: 
                        type: string                        
                        example: "Success"
                      XmlDocumentResult: 
                        type: string                        
                        example: "null"
                      AcsessTokenValue: 
                        type: string                        
                        example: "null"
                      RefreshTokenValue: 
                        type: string                        
                        example: "null"
                      ResponseEmail: 
                        type: string                        
                        example: "null"
                      ResponseMobileNo: 
                        type: string                        
                        example: "null"
                      ResponseUserType_CBEC: 
                        type: string                        
                        example: "null"
                      ResponseFirstName: 
                        type: string                        
                        example: "null"
                      ResponseLastName: 
                        type: string                        
                        example: "null"
                      ResponseCountryCode: 
                        type: string                        
                        example: "null"
                      ResponseUserId: 
                        type: number                        
                        example: 0.0
                      XmlDreports: 
                        type: string                        
                        example: "null"

   
        400:
          description: Bad Request/Validation Error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Text






