
  /{{api.path}}:
    {{api.method}}:
      tags:
      - {{api.tag}}
      summary: {{api.summary}}
      operationId: {{api.operationId}}
      {% if api.authorization != "" %}
       {% if api.authorization|set_security %}
      security:
      - {{api.authorization}}: []
       {% endif %}
      {% endif %}
      parameters:
      {% for key in api.parameters %}
        - in: header
          name: {{key}}
          schema:
            type: {{api.parameters[key]|get_type}}
            example: "{{api.parameters[key]}}"
      {% endfor %}
      requestBody:
        content:
          {{api.content_type}}:
            schema:
            {% if api.content_type == 'multipart/form-data' %}
              type: object
            {% endif %}
              properties:
                {% for key in api.requestBody %}
                  {{key}}:
                    type: {{api.requestBody[key]|get_type}}
                    {% if (api.requestBody[key]|get_type) == 'object' %}
                    properties:
                     {% for obj_param in api.requestBody[key] %}
                      {{obj_param}}:
                        type: {{api.requestBody[key][obj_param]|get_type}}
                        {% if api.requestBody[key][obj_param]|get_type == 'object' %}
                        properties:
                        {% for nested_obj_param in api.requestBody[key][obj_param] %}
                         {{nested_obj_param}}:
                           type: {{nested_obj_param|get_type}}
                           example: {{api.requestBody[key][obj_param][nested_obj_param]}}
                        {% endfor %}
                        {% elif api.requestBody[key][obj_param]|get_type == 'array' %}
                        items:
                          type: object
                          properties:
                           {% for element in api.requestBody[key][obj_param][0] %}
                            {{element}}:
                              type: {{api.requestBody[key][obj_param][0][element]|get_type}}
                           {% endfor %}
                        example:
                        {% for nested_array_param in api.requestBody[key][obj_param] %}
                        {% for element in nested_array_param %}
                          {% if loop.first %}
                        -  {{element}}: {{nested_array_param[element]}}
                          {% else %}
                           {{element}}: {{nested_array_param[element]}}
                          {% endif %}
                        {% endfor %}
                        {% endfor %}
                        {% else %}
                        example: {{api.requestBody[key][obj_param]}}
                        {% endif %}
                     {% endfor %}
                    {% elif (api.requestBody[key]|get_type) == 'array' %}
                    items:
                      type: object
                      properties:
                      {% for element in api.requestBody[key][0] %}
                        {{element}}:
                          type: {{api.requestBody[key][0][element]|get_nestedarray_type}}
                      {% endfor %}
                    example:
                     {% for array_param in api.requestBody[key] %}
                      {% for element in array_param %}
                       {% if loop.first %}
                      -  {{element}}: {{array_param[element]}}
                       {% else %}
                         {{element}}: {{array_param[element]}}
                       {% endif %}
                      {% endfor %}
                     {% endfor %}
                    {% else %}
                    {% if key|get_format != "" %}
                    format: {{key|get_format}}
                    {% endif %}
                    example: {{api.requestBody[key]}}
                    {% endif %}
                {% endfor %}
      responses:
      {% for response_code in api.responses %}
        {{response_code}}:
          {% if response_code|get_description != "" %}
          description: {{response_code|get_description}}
          {% endif %}
          {% if api.responses[response_code] %}
          content:
            application/json:
              schema:
                properties:
                {% for param in api.responses[response_code] %}
                  {{param}}:
                    type: {{api.responses[response_code][param]|get_type}}
                    {% if param|get_description != "" %}
                    description: {{param|get_description}}
                    {% endif %}
                    {% if (api.responses[response_code][param]|get_type) == 'object' %}
                    properties:
                    {% for obj_param in api.responses[response_code][param] %}
                      {{obj_param}}: 
                        type: {{api.responses[response_code][param][obj_param]|get_type}}                        
                        {% if (api.responses[response_code][param][obj_param]|get_type) == 'object' %}
                        properties:
                        {% for nested_obj_param in api.responses[response_code][param][obj_param] %}
                          {{nested_obj_param}}: 
                            type: {{nested_obj_param|get_type}}
                            example: {{api.responses[response_code][param][obj_param][nested_obj_param]}}
                        {% endfor %}
                        {% elif (api.responses[response_code][param][obj_param]|get_type) == 'array' %}
                        items:
                          type: object
                          properties:
                            {% for element in api.responses[response_code][param][obj_param][0] %}
                            {{element}}:
                              type: {{api.responses[response_code][param][obj_param][0][element]|get_type}}
                            {% endfor %}
                        example:
                        {% for nested_array_param in api.responses[response_code][param][obj_param] %}
                        {% for element in nested_array_param %}
                          {% if loop.first %}
                        -  {{element}}: {{nested_array_param[element]}}
                          {% else %}
                           {{element}}: {{nested_array_param[element]}}
                          {% endif %}
                        {% endfor %}
                        {% endfor %}
                        {% else %}
                        example: {{api.responses[response_code][param][obj_param]}}
                        {% endif %}
                    {% endfor %}
                    {% elif (api.responses[response_code][param]|get_type) == 'array' %}
                    items:
                      type: object
                      properties:
                        {% for element in api.responses[response_code][param][0] %}
                        {{element}}:
                          type: {{api.responses[response_code][param][0][element]|get_nestedarray_type}}
                        {% endfor %}
                    example:
                    {% for array_param in api.responses[response_code][param] %}
                     {% for element in array_param %}
                      {% if loop.first %}
                      -  {{element}}: {{array_param[element]}}
                      {% else %}
                         {{element}}: {{array_param[element]}}
                      {% endif %}
                     {% endfor %}
                    {% endfor %}
                    {% else %}
                    example: {{api.responses[response_code][param]}}
                    {% endif %}
                {% endfor %}
          {% endif %}
      {% endfor %}