
  /{{api.path}}:
    {{api.method}}:
      tags:
      - {{api.tag}}
      summary: {{api.summary}}
      operationId: {{api.operationId}}
      {% if api.authorization != "" %}
       {% if api.authorization|set_security %}
      security:
      - {{api.authorization}}: []
       {% endif %}
      {% endif %}
      {% if api.parameters.length != 0 %}
      parameters:
      {% for key in api.parameters %}
        - in: header
          name: {{key}}
          schema:
            type: {{api.parameters[key]|get_type}}
            {% if api.parameters[key]|get_type == 'string' %}
            example: "{{api.parameters[key]}}"
            {% else %}
            example: {{api.parameters[key]}}
            {% endif %}
          {% if key in api.mandatory %}
          required: true
          {% endif %}
      {% endfor %}
      {% endif %}
      requestBody:
        content:
          {{api.content_type}}:
            schema:
            {% if api.content_type == 'multipart/form-data' %}
              type: object
            {% endif %}
            {% if api.content_type == 'application/xml' %}
              $ref: '#/components/schemas/{{ api.requestBody.getroot().tag }}'
            {% else %}
             {% if total_apis == 1 %}
              properties:
                {% for key in api.requestBody %}
                  {{key}}:
                    type: {{api.requestBody[key]|get_type}}
                    {% if (api.requestBody[key]|get_type) == 'object' %}
                    properties:
                     {% for obj_param in api.requestBody[key] %}
                      {{obj_param}}:
                        type: {{api.requestBody[key][obj_param]|get_type}}
                        {% if api.requestBody[key][obj_param]|get_type == 'object' %}
                        properties:
                        {% for nested_obj_param in api.requestBody[key][obj_param] %}
                         {{nested_obj_param}}:
                           type: {{nested_obj_param|get_type}}
                           example: {{api.requestBody[key][obj_param][nested_obj_param]}}
                        {% endfor %}
                        {% elif api.requestBody[key][obj_param]|get_type == 'array' %}
                        items:
                          type: object
                          properties:
                           {% for element in api.requestBody[key][obj_param][0] %}
                            {{element}}:
                              type: {{api.requestBody[key][obj_param][0][element]|get_type}}
                           {% endfor %}
                        example:
                        {% for nested_array_param in api.requestBody[key][obj_param] %}
                        {% for element in nested_array_param %}
                          {% if loop.first %}
                        -  {{element}}: {{nested_array_param[element]}}
                          {% else %}
                           {{element}}: {{nested_array_param[element]}}
                          {% endif %}
                        {% endfor %}
                        {% endfor %}
                        {% else %}
                        example: {{api.requestBody[key][obj_param]}}
                        {% endif %}
                     {% endfor %}
                    {% elif (api.requestBody[key]|get_type) == 'array' %}
                    items:
                      type: object
                      properties:
                      {% for element in api.requestBody[key][0] %}
                        {{element}}:
                          type: {{api.requestBody[key][0][element]|get_nestedarray_type}}
                      {% endfor %}
                    example:
                     {% for array_param in api.requestBody[key] %}
                      {% for element in array_param %}
                       {% if loop.first %}
                      -  {{element}}: {{array_param[element]}}
                       {% else %}
                         {{element}}: {{array_param[element]}}
                       {% endif %}
                      {% endfor %}
                     {% endfor %}
                    {% else %}
                    {% if key|get_format != "" %}
                    format: {{key|get_format}}
                    {% endif %}
                    example: {{api.requestBody[key]}}
                    {% endif %}
                {% endfor %}
             {% elif total_apis>1 %}
              anyOf:
                {% for i in range(total_apis) %}
                {% set i = i + 1 %}
              - $ref: "#/components/schemas/{{api.path}}_{{i}}"
                {% endfor %}
            examples:
              {% for i in range(total_apis) %}
              {% set i = i + 1 %}
              {{api.path}} {{i}}:
                $ref: "#/components/examples/{{api.path}}_{{i}}"
              {% endfor %}
             {% endif %}
            {% endif %}
      responses:
      {% for response_code in api.responses %}
        {{response_code}}:
          {% if response_code|get_description != "" %}
          description: {{response_code|get_description}}
          {% endif %}
          {% if api.responses[response_code] %}
          content:
            {% for content_type in api.responses[response_code] %}
            {{content_type}}:
              schema:
                {% if content_type == "application/json" %}
                {% if api.responses[response_code][content_type]|length > 1 %}
                anyOf:
                {% for i in api.responses[response_code][content_type] %}
                - $ref: "#/components/schemas/{{i}}"
                {% endfor %}
              examples:
                {% for i in api.responses[response_code][content_type] %}
                {{i}}:
                  $ref: "#/components/examples/{{i}}"
                {% endfor %}
                {% else %}
                properties:
                {% for json_object in api.responses[response_code][content_type] %}
                {% for param in api.responses[response_code][content_type][json_object] %}
                  {{param}}:
                    type: {{api.responses[response_code][content_type][json_object][param]|get_type}}
                    {% if (api.responses[response_code][content_type][json_object][param]|get_type) == 'object' %}
                    properties:
                    {% for obj_param in api.responses[response_code][content_type][json_object][param] %}
                      {{obj_param}}: 
                        type: {{api.responses[response_code][content_type][json_object][param][obj_param]|get_type}}                        
                        {% if (api.responses[response_code][content_type][json_object][param][obj_param]|get_type) == 'object' %}
                        properties:
                        {% for nested_obj_param in api.responses[response_code][content_type][json_object][param][obj_param] %}
                          {{nested_obj_param}}: 
                            type: {{nested_obj_param|get_type}}
                            {% if api.responses[response_code][content_type][json_object][param][obj_param][nested_obj_param]|get_type == 'string' %}
                            example: "{{ api.responses[response_code][content_type][json_object][param][obj_param][nested_obj_param] }}"
                            {% else %}
                            example: {{ api.responses[response_code][content_type][json_object][param][obj_param][nested_obj_param] }}
                            {% endif %}
                        {% endfor %}
                        {% elif (api.responses[response_code][content_type][json_object][param][obj_param]|get_type) == 'array' %}
                        items:
                          type: object
                          {% if (api.responses[response_code][content_type][json_object][param][obj_param]|length > 0) and (api.responses[response_code][content_type][json_object][param][obj_param][0]|get_type == 'string') %}
                        example: {{api.responses[response_code][content_type][json_object][param][obj_param]}}
                          {% else %}
                          properties:
                            {% for element in api.responses[response_code][content_type][json_object][param][obj_param][0] %}
                            {{element}}:
                              type: {{api.responses[response_code][content_type][json_object][param][obj_param][0][element]|get_nestedarray_type}}
                            {% endfor %}
                        example:
                        {% for nested_array_param in api.responses[response_code][content_type][json_object][param][obj_param] %}
                        {% for element in nested_array_param %}
                          {% if loop.first %}
                            {% if nested_array_param[element]|get_type == 'string' %}
                        -  {{element}}: "{{nested_array_param[element]}}"
                            {% else %}
                        -  {{element}}: {{nested_array_param[element]}}
                            {% endif %}
                          {% else %}
                            {% if nested_array_param[element]|get_type == 'string' %}
                           {{element}}: "{{nested_array_param[element]}}"
                            {% else %}
                           {{element}}: {{nested_array_param[element]}}
                            {% endif %}
                          {% endif %}
                        {% endfor %}
                        {% endfor %}
                        {% endif %}
                        {% else %}
                        {% if api.responses[response_code][content_type][json_object][param][obj_param]|get_type == 'string' %}
                        example: "{{ api.responses[response_code][content_type][json_object][param][obj_param] }}"
                        {% else %}
                        example: {{ api.responses[response_code][content_type][json_object][param][obj_param] }}
                        {% endif %}
                        {% endif %}
                    {% endfor %}
                    {% elif (api.responses[response_code][content_type][json_object][param]|get_type) == 'array' %}
                    items:
                      type: object
                      properties:
                        {% for element in api.responses[response_code][content_type][json_object][param][0] %}
                        {{element}}:
                          type: {{api.responses[response_code][content_type][json_object][param][0][element]|get_nestedarray_type}}
                        {% endfor %}
                    example:
                    {% for array_param in api.responses[response_code][content_type][json_object][param] %}
                     {% for element in array_param %}
                      {% if loop.first %}
                      -  {{element}}: {{array_param[element]}}
                      {% else %}
                         {{element}}: {{array_param[element]}}
                      {% endif %}
                     {% endfor %}
                    {% endfor %}
                    {% else %}
                    example: {{api.responses[response_code][content_type][json_object][param]}}
                    {% endif %}
                {% endfor %}
                {% endfor %}
                {% endif %}

                {% elif content_type == "application/xml" %}
                  {% if api.responses[response_code][content_type]|length > 1 %}
                anyOf:
                  {% for param in api.responses[response_code][content_type] %}
                  {% set prefix,root = param|get_xml_root_prefix %}
                  - $ref: '#/components/schemas/{{root}}'
                  {% endfor %}
              examples:
                  {% for param in api.responses[response_code][content_type] %}
                  {% set prefix,root = param|get_xml_root_prefix %}
                  {{root}}:
                    $ref: "#/components/examples/{{root}}"
                  {% endfor %}
                  {% else %}
                    {% for param in api.responses[response_code][content_type] %}
                    {% set prefix,root = param|get_xml_root_prefix %}
                  $ref: '#/components/schemas/{{root}}'
                    {% endfor %}
                  {% endif %}
                {% endif %}
            {% endfor %}   
          {% endif %}
      {% endfor %}