
  /{{api.path}}:
    {{api.method}}:
      tags:
      - {{api.tag}}
      summary: {{api.summary}}
      operationId: {{api.operationId}}
      security:
      - bearerAuth: []
      parameters:
      {% for key in api.parameters %}
        - in: header
          name: {{key}}
          schema:
            type: {{api.parameters[key]|get_type}}
            example: {{api.parameters[key]}}
      {% endfor %}
      requestBody:
        content:
          {{api.content_type}}:
            schema:
              properties:
                {% for key in api.requestBody %}
                  {{key}}:
                    type: {{api.requestBody[key]|get_type}}
                    example: {{api.requestBody[key]}}
                {% endfor %}
      responses:
      {% for response_code in api.responses %}
        {{response_code}}:
          {% if response_code|get_description != "" %}
          description: {{response_code|get_description}}
          {% endif %}
          content:
            application/json:
              schema:
                properties:
                {% for param in api.responses[response_code] %}
                  {{param}}:
                    type: {{api.responses[response_code][param]|get_type}}
                    {% if param|get_description != "" %}
                    description: {{param|get_description}}
                    {% endif %}
                    {% if (api.responses[response_code][param]|get_type) == 'object' %}
                    properties:
                    {% for obj_param in api.responses[response_code][param] %}
                      {{obj_param}}: 
                        type: {{api.responses[response_code][param][obj_param]|get_type}}
                        example: {{api.responses[response_code][param][obj_param]}}
                    {% endfor %}
                    {% elif (api.responses[response_code][param]|get_type) == 'array' %}
                    items:
                      type: object
                      properties:
                        {% for element in api.responses[response_code][param][0] %}
                        {{element}}:
                          type: {{api.responses[response_code][param][0][element]|get_type}}
                        {% endfor %}
                    example:
                    {% for array_param in api.responses[response_code][param] %}
                     {% for element in array_param %}
                      {% if loop.first %}
                      -  {{element}}: {{array_param[element]}}
                      {% else %}
                         {{element}}: {{array_param[element]}}
                      {% endif %}
                     {% endfor %}
                    {% endfor %}
                    {% else %}
                    example: {{api.responses[response_code][param]}}
                    {% endif %}
                {% endfor %}
      {% endfor %}